services:
  app:
    container_name: library_management_system
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "9003:9003"  # Xdebug
    environment:
      DATABASE_URL: mysql://user:password@db:3306/app_db
      REDIS_URL: redis://redis:6379
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    depends_on:
      - db
      - redis

  test:
    container_name: library_management_system_test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql://user:password@db:3306/app_db_test
      REDIS_URL: redis://redis:6379
      APP_ENV: test
    depends_on:
      - db
      - redis
    profiles:
      - test

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: