framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # Redis configuration
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
